apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: ph
spec:
  selector:
    website: website
  ports:
    - port: 80 # for cloud
      # - port: 4200 # for local cluster
      targetPort: 4200
  type: LoadBalancer # for cloud
  # type: ClusterIP # for local cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    website: website
  namespace: ph
spec:
  replicas: 1
  selector:
    matchLabels:
      website: website
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        website: website
    spec:
      containers:
        - image: ghcr.io/mcesarczyk/personal-homepage-website:latest
          name: website
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: API_URL
              value: http://app.ph.svc.cluster.local:5000
            - name: API_PREFIX
              value: /api/v1
            - name: NEXT_PUBLIC_API_URL
              value: http://app.ph.svc.cluster.local:5000
            - name: NEXT_PUBLIC_API_PREFIX
              value: /api/v1
